// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqTU0r6BGe6uxo7WSOd7OxQ3ceZpW-ODI',
    appId: '1:576978647108:web:ad0ccbf153e9b12b6d6411',
    messagingSenderId: '576978647108',
    projectId: 'openmemes-305af',
    authDomain: 'openmemes-305af.firebaseapp.com',
    storageBucket: 'openmemes-305af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFbr545Z1WAdtwo1NmtZR1fd7fDN9mwp0',
    appId: '1:576978647108:android:55f956e83d2b93da6d6411',
    messagingSenderId: '576978647108',
    projectId: 'openmemes-305af',
    storageBucket: 'openmemes-305af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjtpf5M4j0VZcqKKP4MNbkxVb7lzKUl9s',
    appId: '1:576978647108:ios:ab358b87d3d561e36d6411',
    messagingSenderId: '576978647108',
    projectId: 'openmemes-305af',
    storageBucket: 'openmemes-305af.appspot.com',
    iosBundleId: 'com.example.flutterApplicationOpenmemes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjtpf5M4j0VZcqKKP4MNbkxVb7lzKUl9s',
    appId: '1:576978647108:ios:caa3451cd42be5866d6411',
    messagingSenderId: '576978647108',
    projectId: 'openmemes-305af',
    storageBucket: 'openmemes-305af.appspot.com',
    iosBundleId: 'com.example.flutterApplicationOpenmemes.RunnerTests',
  );
}
