name: flutter_application_openmemes
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/bglogin.png
    - images/bgmainpage.jpeg
    - images/bggenpage.jpg
    - images/wojak.png
  
  fonts:
    - family: LexendDeca
      fonts:
        - asset: fonts/LexendDeca-Regular.ttf
        - asset: fonts/LexendDeca-VariableFont_wght.ttf



