import 'package:flutter/material.dart';

void main() {
  runApp(const MainPage());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class MainPage extends StatelessWidget {
  const MainPage({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Mobile(),
        ]),
      ),
    );
  }
}

class Mobile extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: const BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 360,
                  height: 800,
                  decoration: const BoxDecoration(
                    image: DecorationImage(
                      image: AssetImage("images/bglogin.png"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 25,
                top: 264,
                child: SizedBox(
                  width: 311,
                  height: 385,
                  child: Text(
                    '¡Presentamos el generador de memes definitivo impulsado por OpenAI Enhancement y el repositorio Memegen GitHub!                    ¿Estás listo para llevar tu juego de memes al siguiente nivel? No busque más, nuestro generador de memes de vanguardia, que combina las increíbles capacidades de los algoritmos avanzados de OpenAI con la vasta y diversa biblioteca de memes del repositorio Memegen GitHub.',
                    textAlign: TextAlign.justify,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 20,
                      fontFamily: 'LexendDeca',
                      fontWeight: FontWeight.w400,
                      height: 0,
                    ),
                  ),
                ),
              ),
              const Positioned(
                left: 29,
                top: 98,
                child: SizedBox(
                  width: 302,
                  height: 119,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: 'Open\nMemes',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 48,
                            fontFamily: 'LexendDeca',
                            fontWeight: FontWeight.w600,
                            height: 0,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 25,
                top: 693,
                child: SizedBox(
                  width: 311,
                  height: 61,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 311,
                          height: 61,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFDEC6C6),
                            shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(6)),
                          ),
                        ),
                      ),
                      const Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 284.03,
                          height: 61,
                          child: Text(
                            'Comienza a crear tus Memes!!!',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 20,
                              fontFamily: 'LexendDeca',
                              fontWeight: FontWeight.w400,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
